name: Compile OpenBLAS on MacOS x86_64
run-name: Compile OpenBLAS on MacOS x86_64 - ${{ github.sha }}
on: workflow_dispatch
jobs:
  compile_openblas:
    strategy:
      matrix:
        arch:
          - [x86_64, SANDYBRIDGE]
    name: ${{ matrix.arch[0] }}
    runs-on: macos-11
    steps:
      - name: Compile OpenBLAS
        env:
          MACOSX_DEPLOYMENT_TARGET: "10.9"
        run: |
          curl -L -o OpenBLAS-0.3.25.tar.gz https://github.com/OpenMathLib/OpenBLAS/releases/download/v0.3.25/OpenBLAS-0.3.25.tar.gz
          tar -xzf OpenBLAS-0.3.25.tar.gz
          sudo ln -fs /usr/local/bin/gfortran-11 /usr/local/bin/gfortran
          make -C OpenBLAS-0.3.25 TARGET=${{ matrix.arch[1] }} DYNAMIC_ARCH=1
          make install -C OpenBLAS-0.3.25 PREFIX=${GITHUB_WORKSPACE}/OpenBLAS

      - name: Upload artifacts
        uses: actions/upload-artifact@v3.1.3
        with:
          name: OpenBLAS_macos_${{ matrix.arch[0] }}
          path: ./OpenBLAS
          if-no-files-found: error
